### ISSUE TITLE
Add bounds and center to metadata in MBTiles file

### ISSUE THREAD

**Issue by ssokol** [N129BZ/chartmaker#14]
Not a huge deal, but having the bounds and center coordinates in the metadata would make it slightly faster for my use case. My tile server indexes the MBTiles files in a given directory then uses the bounds and/or center values to find the required file when it receives a request.

Here's what tilemaker sets as metadata for those values:

```
bounds|-106.645646,25.837377,-93.508292,36.500704
center|-100.076969,31.169041,7
```

**Comment by N129BZ** [comment]
Some clarification please... are you referring to the individual VFR Sectional charts, the full VFR Sectional, or some other chart(s)? 

I would also want to make sure any new enhancement would not collide with the Stratux integration feature the and "own aircraft position" recording feature (enabled in settings.) With that feature enabled, the map opens up to the last recorded position of your aircraft, as reported by Stratux.  I am assuming that with this additional bounds data in the metadata, it would have to be with Stratux integration turned off...

**Comment by N129BZ** [comment]
The reason I ask about whether you are referring to the full US sectional is that it's actually stitched together from 53 individual geotiffs which are then merged, each of which has bounds coordinates...

**Comment by N129BZ** [comment]
The FAA charts give the bounds of each chart as:
**_lat, lng: upper left
lat, lng: upper right
lat, lng: lower right
lat, lng: lower left_**

So, what would you prefer?  Upper left and Lower right, plus a calculated center?

**Comment by N129BZ** [comment]
If processing single area chart(s), the app will now add bounds and center values to the metadata table in each mbtiles database.  
These new metadata fields will be not be present if processing any of the full charts, since those are actually comprised of multiple individual geotiffs which each have individual extent data, making any overall calculation of extents more involved than I have time or inclination to deal with.

**Comment by N129BZ** [comment]
P.S., also added a new settings.json key+value: **_centerzoomlevel_** which defaults to **7**.   Example below.
![metadata](https://github.com/user-attachments/assets/238b7bbc-88a1-4144-9d2f-97a82a7ebbc5)

**Comment by ssokol** [comment]
Apologies - I was out for part of the weekend. I was specifically referring to the bounds for individual VFR sectionals. What you've added is exactly what I needed. Thank you very much!
