### ISSUE TITLE
Hey! I can confirm the sectional chart process is working now but I get an error when processing enroute low and enroute high?

### ISSUE THREAD

**Issue by N129BZ** [N129BZ/chartmaker#15]
Hey! I can confirm the sectional chart process is working now but I get an error when processing enroute low and enroute high?

```
Your selection: 3

Select the full chart number you want to process from this list

0 Sectional
1 Caribbean
2 Grand Canyon
3 Terminal
4 Helicopter
5 Enroute Low
6 Enroute High
7 US VFR Wall Planning
--------------------------------------------
Your selection: 5 
/chartmaker/make.js:318
        let lcasename = chart[index].toLowerCase(); 
                                     ^

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at /chartmaker/make.js:318:38
    at Array.forEach (<anonymous>)
    at processFulls (/chartmaker/make.js:316:12)
    at processOneFull (/chartmaker/make.js:312:5)
    at Object.<anonymous> (/chartmaker/make.js:237:13)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)

Node.js v20.17.0
root@91dabe07f0a2:/chartmaker# node make
Select:
-----------
```

_Originally posted by @idouiri9806 in https://github.com/N129BZ/chartmaker/issues/13#issuecomment-2393372605_

**Comment by N129BZ** [comment]
FIxed bug in Full chart processing where the chartname is supposed to be converted to lower case. The IFR charts are unique in that a single FAA zip file, DDECUS, contains both the enroute_low and enroute_high chart TIFFs. The processing needs to know the name of the chart file, but needs to isolate the selected chart type from those 2 different types of charts and convert that "sub chart type" name to lower case.

**Comment by idouiri9806** [comment]
@N129BZ Yes! It is working beautifully! Thank you! Just one question: are the IFR low and high charts for Alaska not included? Apologies for the late reply—we're constantly getting rocked by weather down southeast.
