### ISSUE TITLE
Add valid and expires dates to metadata

### ISSUE THREAD

**Issue by ssokol** [N129BZ/chartmaker#16]
Not at all a priority, but when you're doing the next bit of maintenance to the code, it would be great if the metadata included the date that the chart becomes valid / active, and the date that it expires. Something like:

```
valid|2024-10-31
expires|2024-11-28
```

**Comment by ssokol** [comment]
Another fixed value that would be useful to have in the metadata is the scheme. Chartmaker seems to use the TMS scheme so:

```
scheme|tms
```

**Comment by N129BZ** [comment]
Added valid date, expire date, and scheme fields to the metadata table.

**Comment by N129BZ** [comment]
P.S. - now updating the docker image.
