### ISSUE TITLE
support for IFR (enroute) charts

### ISSUE THREAD

**Issue by rolandoam** [N129BZ/chartmaker#2]
Hi!

Thanks for putting this together! really useful. I ended up setting a docker container and creating a small script to fetch VFR charts. I was attempting to update this to support dowloading and processing enroute charts but I got stuck on where to create/find the shapes to trim the individual charts, did you build those manually? if so, any suggestions on how to get those done fore IFR charts?

**Comment by N129BZ** [comment]
Hi Rolando,

The image processing uses what are called clip files to render all of the border stuff, legends, etc., as alpha channel (invisible.)  Each chart needs its own set of clip files. For instance you can see the sectional clip files at: 

https://github.com/N129BZ/chartmaker/tree/main/clipshapes/Sectional

Clip files are generated using an app like arcGIS. 
See: https://desktop.arcgis.com/en/arcmap/10.3/tools/data-management-toolbox/clip.htm

**Comment by rolandoam** [comment]
got it! thanks :) 
I think as a start I'll skip clipping and try to see if I can get the enroute charts layed over the map.
