### ISSUE TITLE
Docker pull command return error

### ISSUE THREAD

**Issue by ssokol** [N129BZ/chartmaker#6]
Hi Brian,

Sorry to be a pain. I tried using the container search function in the Docker Desktop app, but it only showed tag version 1.20. I tried running the pull command manually from the terminal (on a Mac) and got:

```
ssokol@Stevens-MacBook-Pro-2 Downloads % docker pull n129bz/chartmaker:v1.25
Error response from daemon: manifest for n129bz/chartmaker:v1.25 not found: manifest unknown: manifest unknown
```

I was able to download 1.20 from the main docker registry but it does not want to run for some reason - possibly because I'm on an ARM64 Mac and the image was created for AMD64?

**Comment by N129BZ** [comment]
Try using the --platform switch when running, see:

https://stackoverflow.com/questions/67458621/how-to-run-amd64-docker-image-on-arm64-host-platform#:~:text=Running%20amd64%20images%20is%20enabled,specific%20container%20you're%20using.

**Comment by N129BZ** [comment]
Also see: https://www.reddit.com/r/docker/comments/td0w9t/running_amd64_containers_on_arm64_machine/

**Comment by N129BZ** [comment]
Also - I need to build a new docker image with the latest release which includes the new command line functionality and individual state chart processing.  Should be done later today. I'll post the link then.

**Comment by N129BZ** [comment]
New docker image pushed, n129bz/chartmaker:v1.34, found at:
[https://hub.docker.com/repository/docker/n129bz/chartmaker/general](url)    

To run on Mac ARM64, use the --platform option when launching, 

_**docker run -it --platform linux/amd64 n129bz/charmaker:v1.34**_   

This image has the newest version of Chartmaker with new command line options and individual VFR area chart capability.    

Closing issue.

**Comment by N129BZ** [comment]
Docker image now updated to version 1.35
https://hub.docker.com/repository/docker/n129bz/chartmaker/general
