### ISSUE TITLE
Project idea: terrainmaker?

### ISSUE THREAD

**Issue by ssokol** [N129BZ/chartmaker#7]
Brian and Jim,

Do either of you have any interest in adding terrain data to your projects? I'm currently kicking around options for adding both 2D terrain (hillshade) with custom shaders for above/below and also 3D terrain for synthetic vision. I'm still looking at options for the display client but at this point MapLibre GL JS is in the lead.

What's harder to find is a good source for the DEM data in a format that's small enough to pack onto a Flash drive and available in reasonably downloadable sections. Might either of you care to work on something like that?

Best Regards,

Steve

P.S. - Apologies for abusing the issue system here, but I don't think Github provides any other way of directly communicating.

**Comment by N129BZ** [comment]
Steve - when you create an issue, click on the Labels gear icon, from there you can change the label to "enhancement"

**Comment by ssokol** [comment]
I would have, but non-contributor users don't have the option to set labels, etc. I can do so on issues in my own repos, but I don't get the gear icon when I go to create an issue in chartmaker.

**Comment by N129BZ** [comment]
AHA!! I didn't know that... I have added you as a collaberator, if you approve you should be able to set labels etc.

**Comment by N129BZ** [comment]
I'm looking into OpenLayers Cesium for my map viewing application, https://github.com/n129bz/chartserver 
From what I've been reading, Cesium has 3d terrain capabilities for the entire globe, but it's going to take me a while to digest everything.

**Comment by ssokol** [comment]
I did some playing with Cesium a couple of years ago. Here's a quick demo on their Sandcastle playground system:

https://t.ly/LkDPn

It's definitely complex and capable. I didn't get far enough into it to figure out how to build and host offline DEM data, but I'm fairly sure it can be done.

**Comment by jamez70** [comment]
I'm still working on my map https://linair.net/map . I am working on TFRs
and AIRMETs currently.

**Comment by ssokol** [comment]
Looks like there's a rather old project called Cesium Terrain Builder that can generate the data it uses. There's also a Docker container version:

[https://github.com/geo-data/cesium-terrain-builder](https://github.com/geo-data/cesium-terrain-builder)
[https://github.com/tum-gis/cesium-terrain-builder-docker](https://github.com/tum-gis/cesium-terrain-builder-docker)
