### ISSUE TITLE
Conversions a little grainy at high zoom levels

### ISSUE THREAD

**Issue by jamez70** [N129BZ/chartmaker#9]
Here is a clip from the `.tif` file:

![image](https://github.com/user-attachments/assets/7eae8e1d-bae4-490b-a9b6-4bc412924973)

Here is the same area roughly with 100% quality tiles. Ignore the marker over the airport as this is my app displaying the weather there.

![image](https://github.com/user-attachments/assets/b06c3ec2-6617-4f11-a151-d6ab8808febb)

What causes the degradation of the quality? Can it be improved at all?

**Comment by N129BZ** [comment]
What is the image type being generated?

**Comment by jamez70** [comment]
I've tried webp and png and had the same results

**Comment by N129BZ** [comment]
I'm looking into this, from what I'm finding its a known issue with gdal.  It may relate to some metadata in the GeoTIFF source.  Some GeoTIFFs have a device block size value that is not 256 x 256 px. - I'm looking at them using gdalinfo to see what I can find.

**Comment by N129BZ** [comment]
Here is the metadata from wichita.vrt below.  Note the X and Y resolutions.  I believe gdal_translate defaults to 256x256, so it maybe has some some negative effect on the resulting tiled images that they're not being translated to the original dimensions.  I'm going to experiment with reading the metadata and setting the BLOCKXSIZE and BLOCKYSIZE parameters to match the metadata values:
<Metadata>
    <MDI key="AREA_OR_POINT">Area</MDI>
    <MDI key="TIFFTAG_DATETIME">2024:06:11 11:20:03</MDI>
    <MDI key="TIFFTAG_RESOLUTIONUNIT">2 (pixels/inch)</MDI>
    <MDI key="TIFFTAG_SOFTWARE">Adobe Photoshop 24.6 (Windows)</MDI>
    <MDI key="TIFFTAG_XRESOLUTION">300</MDI>
    <MDI key="TIFFTAG_YRESOLUTION">300</MDI>
  </Metadata>

**Comment by jamez70** [comment]
Oh nice! I'd just like to be as good as skyvector or vfrmap is. It actually does look like a downsampling algorithm is causing it because of the way the edges appear

**Comment by N129BZ** [comment]
jamez70 - please test this new docker image: **_n129bz/chartmaker:v1.37_**

I added LZW lossless compression and several more -co options in the gdal_translate, gdalwarp, and gdaladdo commands, as well as upping the default zoomlevel from 1-12 to 1-13 and the default tileimagequality to 100.  I think the results are definitely better, but would like a 2nd pair of eyes on this...

**Comment by jamez70** [comment]
I tried but it says
`Error response from daemon: manifest for n129bz/chartmaker:v1.37 not found: manifest unknown: manifest unknown`

**Comment by N129BZ** [comment]
Yes, it’s not there yet.  I edited the comment and mentioned it’ll be there in an hour.

**Comment by jamez70** [comment]
Oh no problem. I'll try it tonight

**Comment by N129BZ** [comment]
Sorry about the delay, I decided to make the new image from scratch. It's up now

**Comment by jamez70** [comment]
No big deal. I'll try it later and let you know

Jim

**Comment by jamez70** [comment]
I tried.. It wasn't able to get any image

**Comment by N129BZ** [comment]
So sorry for the delay.  I ended up revamping the logic for dealing with passed arguments.  I was using the asterisk as an arg to process all 53 individual area charts and discovered it blew up when running in docker (worked fine in WSL so I never caught that.)

new image is **_n129bz/chartmaker:v1.38_**

New values for a passed arg are ALL, SINGLE=X (where X is the chart number) or FULL to process whatever indexes are in the chartprocessindexes array.  No passed arg defaults to the prompt for the process you want.

I also re-indexed the vfrindividualcharts array in settings.json to be zero-based like all the other arrays in there.   All of the other (hopeful) improvements to image processing are still there from my original v1.36 attempt...

Thanks for your patience and time!!

--Brian

**Comment by jamez70** [comment]
I totally understand. In the meantime I just updated the git files in 1.36
and I'm running that right now.

**Comment by N129BZ** [comment]
Here's what I got:
![BurlingtonMuni](https://github.com/user-attachments/assets/5dd7aab9-9fe5-4641-abe6-526d060e4387)

**Comment by N129BZ** [comment]
Here's what I got:
![BurlingtonMuni](https://github.com/user-attachments/assets/41b2f89a-344c-4c26-9ed4-af93502eb343)

**Comment by N129BZ** [comment]
A little more zoomed:
![BurlingtonMuni2](https://github.com/user-attachments/assets/55a09d3a-f277-40ac-a5e0-1f274107da80)

**Comment by N129BZ** [comment]
and a little more:
![BurlingtonMuni3](https://github.com/user-attachments/assets/e70a8002-4aa4-4947-98b5-57c51669c9bd)

**Comment by jamez70** [comment]
wow that looks perfect! and I am very impressed! Nice work!

**Comment by N129BZ** [comment]
The only "gotcha" is bigger db files... I think changing zoom level from 12 to 14 adds a lot of size.  Closing issue
